name: book_app
description: "book_app is collection books."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc:
  flutter_bloc:
  equatable:
  internet_connection_checker: ^3.0.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  crystal_navigation_bar: ^1.0.2
  iconly: ^1.0.1
  font_awesome_flutter: ^10.6.0
  dartz: ^0.10.1
  dio:
  get_it: ^8.0.3
  cached_network_image: ^3.4.1
  go_router: ^14.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: montserrat
      fonts:
        - asset: assets/font/montserrat-semiBold.ttf
    - family: gt
      fonts:
        - asset: assets/font/gt.ttf
